name: Checks

on: push

# env:
#   DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
#   DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}


jobs:
  test-lint:
    name: Test and Lint
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      # - name: Set up environment variables in dedicated file
      #   run:
      #     echo DOCKER_USERNAME=${DOCKER_USERNAME} >> $GITHUB_ENV
      #     echo DOCKER_PASSWORD=${DOCKER_PASSWORD} >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # registry: 'https://index.docker.io/v2/'
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"