name: Checks

on: push



jobs:
  test-lint:
    name: Test and Lint
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Set up environment variables in dedicated file
        run:
          echo DOCKER_USERNAME=${DOCKER_USERNAME} >> $GITHUB_ENV
          echo DOCKER_PASSWORD=${DOCKER_PASSWORD} >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: 'https://index.docker.io/v2/'
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"